create table Address (id int8 generated by default as identity, city varchar(255), employee_id int8, number int4, primary key (id));
create table Employee_nickNames (Employee_id int8 not null, nickNames varchar(255));
create table Employee_phoneNumbers (Employee_id int8 not null, phoneNumbers varchar(255), phoneNumbers_KEY varchar(255) not null, primary key (Employee_id, phoneNumbers_KEY));
create table Employee_vacationBookings (Employee_id int8 not null, daysTaken int4 not null, startDate date);
create table employees (id int8 generated by default as identity, emp_name varchar(255), primary key (id));
alter table if exists Address add constraint FK2fjtfgsttl7ps4jgjvxgb9qgc foreign key (employee_id) references employees;
alter table if exists Employee_nickNames add constraint FKk2ho3hpxgoxcx8xeq4tcp5mdj foreign key (Employee_id) references employees;
alter table if exists Employee_phoneNumbers add constraint FK1r1feri6axq651edeiviepckb foreign key (Employee_id) references employees;
alter table if exists Employee_vacationBookings add constraint FKotv1vf83ktwk6fkqjga4b1eou foreign key (Employee_id) references employees;
